const titles={overview:"Command Center",traffic:"Traffic AI",parking:"Smart Parking",safety:"Safety & AI Vision",waste:"Waste Network",energy:"Energy Grid",devices:"IoT Fleet"};
function showSection(id){document.querySelectorAll(".section").forEach(s=>s.classList.remove("active"));document.getElementById(id).classList.add("active");document.querySelectorAll(".nav").forEach(n=>n.classList.toggle("active",n.dataset.section===id));document.getElementById("title").textContent=titles[id];window.scrollTo({top:0,behavior:"smooth"})}
document.querySelectorAll(".nav").forEach(n=>n.addEventListener("click",()=>showSection(n.dataset.section)));

const activity=new Chart(document.getElementById("activityChart"),{type:"line",data:{labels:["00","03","06","09","12","15","18","21","Now"],datasets:[{data:[18,12,21,38,44,52,71,56,64],tension:.38,borderColor:"#9df5d0",backgroundColor:"#9df5d01c",fill:true,pointRadius:2,pointBackgroundColor:"#9df5d0",borderWidth:2}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{grid:{display:false},ticks:{color:"#60757e",font:{size:8}}},y:{grid:{color:"#182a33"},ticks:{color:"#60757e",font:{size:8}}}}}});
const energy=new Chart(document.getElementById("energyChart"),{type:"bar",data:{labels:["Mon","Tue","Wed","Thu","Fri","Sat","Sun"],datasets:[{label:"Demand",data:[74,78,71,69,64,57,68],backgroundColor:"#6db7ff99",borderRadius:5},{label:"Solar",data:[28,31,35,39,43,47,43],backgroundColor:"#9df5d099",borderRadius:5}]},options:{responsive:true,plugins:{legend:{labels:{color:"#8fa3aa",font:{size:9}}}},scales:{x:{grid:{display:false},ticks:{color:"#60757e"}},y:{grid:{color:"#182a33"},ticks:{color:"#60757e"}}}}});

function toast(msg){const t=document.getElementById("toast");t.textContent=msg;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2400)}
let events=64;
setInterval(()=>{events+=Math.floor(Math.random()*7)-2;events=Math.max(40,events);document.getElementById("devicesMetric").textContent=(1240+Math.floor(Math.random()*18)).toLocaleString();document.getElementById("mobilityMetric").textContent=68+Math.floor(Math.random()*9);document.getElementById("energyMetric").textContent=(79+Math.random()*5).toFixed(1)+"%";document.getElementById("lastSync").textContent="just now"},3500);

document.getElementById("simulateBtn").onclick=()=>{document.getElementById("alertsMetric").textContent="08";const box=document.getElementById("alertList");const el=document.createElement("div");el.className="alert critical";el.innerHTML="<b>⚡ Simulated IoT anomaly</b><span>ESP32-TEST-01 · just now</span><small>NEW</small>";box.prepend(el);toast("New sensor event received");};
document.getElementById("clearAlerts").onclick=()=>{document.getElementById("alertList").innerHTML="<div class='alert'><b>✓ Alert queue cleared</b><span>Demo alerts archived locally.</span><small>DONE</small></div>";document.getElementById("alertsMetric").textContent="00";toast("Demo alert queue cleared");};
document.getElementById("addDevice").onclick=()=>{const id="SC-ESP32-"+Math.floor(100+Math.random()*899);const row=document.createElement("tr");row.innerHTML="<td>"+id+"</td><td>New Zone</td><td>ESP32 IoT Node</td><td><b class='good'>● Online</b></td><td>just now</td><td>31°C · 58%</td>";document.getElementById("deviceRows").prepend(row);toast(id+" registered successfully");};

const modal=document.getElementById("modal");document.getElementById("searchBtn").onclick=()=>modal.classList.add("open");document.getElementById("closeModal").onclick=()=>modal.classList.remove("open");modal.onclick=e=>{if(e.target===modal)modal.classList.remove("open")};
document.getElementById("searchInput").oninput=e=>{const q=e.target.value.toLowerCase();const data=["SC-ESP32-204 · Central · Traffic Sensor","SC-CAM-118 · North · AI Camera","SC-PRK-077 · Metro · Parking Node","SC-ENR-041 · Zone 04 · Energy Meter","Central Junction · Traffic alert","Market Road · Waste Zone"];document.getElementById("searchResults").innerHTML=(q?data.filter(x=>x.toLowerCase().includes(q)):data).map(x=>"<div class='result'>"+x+"</div>").join("")};
document.getElementById("notifyBtn").onclick=()=>toast("3 notifications: 2 critical, 1 review");
document.getElementById("themeBtn").onclick=()=>{document.body.classList.toggle("light");toast("Theme preview toggled")};
document.addEventListener("keydown",e=>{if(e.key==="Escape")modal.classList.remove("open")});